### ISSUE TITLE
Caller pressed: 000

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#13] opened 2024-01-18 20:04 UTC
I am now having some luck now with the voice messaging and pressing 0 to be permitted. Hurrah!

So far, my limited testing is from my LG V40 cell phone and my wife's Kyocera DuraXE flip phone. The V40 seems to work as intended/expected. However, every time I press 0 on the DuraXE, callattendant registers more than one 0 on the single key press. Last time was 3 of them, other times even more. I know this as on the console I see the following (which appears to come out of voicemail.py's voice_messaging_menu() function) right after self.modem.wait_for_keypress() is invoked:

    Caller pressed: 000

When I look at modem.py's wait_for_keypress(), it looks like it should be ignoring any save the 1st digit:

if len(digit_list) > 0:
    return True, digit_list[0]

But it seems that more than just one digit is being returned (and then being printed to the console). And if this is the case, the following tests of digit against a single character in voicemail.py's voice_messaging_menu() will not work as expected.

I do not know, but I suspect this has something to do with how the DuraXE sends DTMF. Perhaps this affects other phones as well? Anyone else see this?

Thanks

**Comment by whitedavidp** [comment] 2024-01-18 20:22
I was just able to test using a Samsung s8+ and it behaves the same as the DuraXE. Very strange...

I cannot help but wonder if our new fiber optic phone service and its gateway are somehow involved. But the fact that it doesn't happen on all phones seems to point the finger elsewhere.

I wonder if the tests occurring in voicemail.py's voice_messaging_menu() like this:

if digit == '1':

might not be able to be changed to something like:

if digit.startswith("1")

?

I have tried implementing this and it appears to work on otherwise recalcitrant phones and does not appear to break the LG V40 that was working previously.

**Comment by thess** [comment] 2024-01-18 21:45
This is most fun - I don't think it's phone related. DTMF doesn't do that. It must be the modem sending the `000` as a single item. Since I have only tested Conexant devices, I need to dig into the USR doc to see if this makes sense. In the meantime, your fix looks reasonable for now.

**Comment by whitedavidp** [comment] 2024-01-18 21:56
> This is most fun - I don't think it's phone related. DTMF doesn't do that. It must be the modem sending the `000` as a single item. Since I have only tested Conexant devices, I need to dig into the USR doc to see if this makes sense. In the meantime, your fix looks reasonable for now.

Well, you clearly know more than I do about all of this. But for some reason, the one phone (LG V40) worked every time but the other two did not every time. That is, until I put in my "fix" and now all is working well - seemingly every time.

Unless there is a downside to this, it might make sense to test with startswith() in all cases. Cheers

**Comment by thess** [comment] 2024-01-18 22:57
Documentation on how various modems report DTMF codes is sketchy at best. It may be a repeat interval or something else. In your setup, what do you see if you were to press 1 or # ?? For example: could it be `001` or `111`. Depending on the result, I can fix the code.

**Comment by whitedavidp** [comment] 2024-01-19 01:47
Well on my Samsung S8+ (and in all the other cases) I saw repeated sets - always the same single character:

>>Caller pressed: 777
>>Caller pressed: 55
>>Caller pressed: ###

I saw the same pattern on the DuraXE but haven't gone back to test # and others. I strongly suspect it will be similar - ie, repeated sequences of the same character.

On the other hand, from my LG V40 I never seem to get more than a single character:

>>Caller pressed: 7
>>Caller pressed: 5
>>Caller pressed: #

All of this is odd to me. I went googling around and almost instantly found [this page](https://iotbytes.wordpress.com/modem-events-and-dtmf-tone-detection-with-raspberry-pi/). Item 4.2 DTMF Digits speaks to this and shows examples with repeated characters "The DTMF digits are shielded between “/” and  “\~” special characters (For ex: /1111111~ or /5555555~ etc.)."

I am starting to think this is all over the map possibly depending on the sending handset AND the modem (and possibly also VOIP gateways just for fun). So far, my use of startswith() has worked every time on all of my phones.

This doesn't have anything to do with "Upgrade to Python3 strings vs. bytes in modem handling." from your fork's changes? I have no idea but I did see that and wondered.

Thanks for all. Sorry for all the bother and questions.

**Comment by thess** [comment] 2024-01-19 14:16
Thanks for the additional testing. You have confirmed what I suspected. That is, the modem is timing the duration of the keypress by replicating the digits using some time-interval which I believe is tweakable. You will notice that in Pradeep's example only a single digit is displayed as opposed to what is mentioned in the text of the article. His blog was really helpful in that it provided good examples which were used by the original author (emxsys) of Callattendant and myself.

DTMF tones are generated by the originating instrument (phone). They are simply audio passed thru the network to be interpreted by the receiver. There is no additional processing done by intermediaries (ATA or VOIP equipment). I suspect phones send DTMF tones either as long as you hold the a key down or are a one-shot tone burst. That would explain what you see. Also, I think USRobotics and Conexant modems report keypress duration differently - sigh... On my Conexant modem, I see long keypress events as a series of shielded digits rather than strings. In any event, I have a simpler solution than "startswith()" which works in both cases.

Your comment about Python strings vs. bytes has no relevance here. The addition of bytes types to Python was to make buffer and C-style string interfaces to external/system services more efficient.  

I just love writing device handlers for poorly documented hardware ;)

**Comment by whitedavidp** [comment] 2024-01-19 14:42
Good morning (at least it is still morning here in Seattle, WA USA). I really know very little about telephony stuff - this despite working for such a company, Teltone, for maybe 8 months as a contractor. But I did business application programming, not telephony.

I will await seeing these changes show up before trying to update my "working" install. With your fix to the modem, the whole screening thing is working super. I have managed, with your help, to synthesize a new screening and voice mail callback .wav files. At least initially, I am planning to only support the 0 keypress. In having others test my screening (and I fell into this as well), we were all pressing 0 too soon and hanging up before getting the confirmation that 0 had been pressed (which never came because 0 was pressed too soon and then too soon hung up. It seems that the modem/system cannot "listen" while it is "speaking" and that makes sense to me. Anyhow, I think I have that worked out better now. Of course, if folks do not listen to the entire message, there is nothing one can do...

Thanks again for all. This is just a great improvement in our lives!

**Comment by thess** [comment] 2024-01-19 16:54
Actually, when playing audio and either a local extension goes off-hook or caller presses a key, the audio playback will try to be aborted. Any buffered audio will still be happening. The specific keypress is not handled anywhere -- maybe you could add a feature to do that. PRs welcome.

**Comment by whitedavidp** [comment] 2024-01-19 18:15
I was thinking that perhaps something in the config file like:

#VOICE_MAIL_SUPPORTED_KEYS = ('1', '0', '#' )

in my own case it would be:

VOICE_MAIL_SUPPORTED_KEYS = ('0', ) 

And then these modest changes in voicemail.py's voice_messaging_menu() function:

     supported_keys = ('0', )
     while tries < 3:
            success, digit = self.modem.wait_for_keypress(wait_secs)
            if not success:
                break

            print(">>Caller pressed: {}".format(digit))

            if digit == '1' and '1' in supported_keys:
                self.record_message(call_no, caller, self.config["VOICE_MAIL_LEAVE_MESSAGE_FILE"])
                break

            elif digit == '0' and '0' in supported_keys:
                # Save caller to whitelist
                self.whitelist.add_caller(caller, "Caller pressed 0")
                self.modem.play_audio(voice_mail_callback_file)
                self.modem.play_audio(goodbye_file)
                break

            elif digit == '#' and '#' in supported_keys:
                self.modem.play_audio(goodbye_file)
                break

            else:
                # Try again--up to a limit
                self.modem.play_audio(invalid_response_file)
                tries += 1

Might be a good thing?

I suppose that the configuration file might prefer to use symbolic names for the keys to be more user-friendly... I don't know anything yet about the config file processing. But supported_keys would replace my literal with the right value...

**Comment by whitedavidp** [comment] 2024-01-19 18:25
> Thanks for the additional testing. You have confirmed what I suspected. That is, the modem is timing the duration of the keypress by replicating the digits using some time-interval which I believe is tweakable. You will notice that in Pradeep's example only a single digit is displayed as opposed to what is mentioned in the text of the article. His blog was really helpful in that it provided good examples which were used by the original author (emxsys) of Callattendant and myself.
> 
> DTMF tones are generated by the originating instrument (phone). They are simply audio passed thru the network to be interpreted by the receiver. There is no additional processing done by intermediaries (ATA or VOIP equipment). I suspect phones send DTMF tones either as long as you hold the a key down or are a one-shot tone burst. That would explain what you see. Also, I think USRobotics and Conexant modems report keypress duration differently - sigh... On my Conexant modem, I see long keypress events as a series of shielded digits rather than strings. In any event, I have a simpler solution than "startswith()" which works in both cases.
> 
> Your comment about Python strings vs. bytes has no relevance here. The addition of bytes types to Python was to make buffer and C-style string interfaces to external/system services more efficient.
> 
> I just love writing device handlers for poorly documented hardware ;)

I just tested this after doing a clean install (as you said to do it - easy - thanks). Tested on both LG V40 and Samsung S8+. It seems to work as well as the startswith() I was using yesterday. Most excellent. Thanks!

**Comment by thess** [comment] 2024-01-19 20:52
Regarding https://github.com/thess/callattendant/issues/13#issuecomment-1900880836 suggestion...
If this is important to you it's time get your `git` mojo working.
- Fork this repo and clone it
- Create a test branch for your mods
- hack, hack, test, hack some more, test again
- Commit and push your changes to your forked repo (new branch).
   Ref: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
  (It's best to create a branch for each feature or bug fix you are creating.)
- Create a Pull Request for this (upstream) repo
- We can review and discuss with a better workflow as a PR rather than a "random note - go figure" submission.

Never to old to learn ;)

**Comment by thess** [comment] 2024-01-19 20:55
Closed by: ca5291d6df692c4423df45dc112155996b3b5ee8
>Modem can report keypress as a repeated character string instead of a single digit.
Return only the first character in the string.

**Closed as completed by thess** 2024-01-19 20:55 UTC
Labels: bug

**Comment by whitedavidp** [comment] 2024-01-19 21:06
> Regarding [#13 (comment)](https://github.com/thess/callattendant/issues/13#issuecomment-1900880836) suggestion... If this is important to you it's time get your `git` mojo working.
> 
>     * Fork this repo and clone it
> 
>     * Create a test branch for your mods
> 
>     * hack, hack, test, hack some more, test again
> 
>     * Commit and push your changes to your forked repo (new branch).
>       Ref: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
>       (It's best to create a branch for each feature or bug fix you are creating.)
> 
>     * Create a Pull Request for this (upstream) repo
> 
>     * We can review and discuss with a better workflow as a PR rather than a "random note - go figure" submission.
> 
> 
> Never to old to learn ;)

I git that, thanks :-)

I guess I am wondering if, as the keeper of this fork, you think it worth doing/incorporating? No sense if doing all of that if it is just a one-off for me...

Cheers
